// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4eFX36HIl0pbzMitw8QfZk6KzfQqs6fI',
    appId: '1:500529995449:web:8ed737bf2b42526fcdc568',
    messagingSenderId: '500529995449',
    projectId: 'band-room-b6699',
    authDomain: 'band-room-b6699.firebaseapp.com',
    storageBucket: 'band-room-b6699.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiOq5-AyHrLEbDAgq9du01BNkg09FJwlM',
    appId: '1:500529995449:android:28c02e4feff7a48fcdc568',
    messagingSenderId: '500529995449',
    projectId: 'band-room-b6699',
    storageBucket: 'band-room-b6699.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnOIcyEWOzHdKmsMsbQ1gFjAik36Rczvc',
    appId: '1:500529995449:ios:a79f875f4d315ec2cdc568',
    messagingSenderId: '500529995449',
    projectId: 'band-room-b6699',
    storageBucket: 'band-room-b6699.firebasestorage.app',
    iosBundleId: 'com.example.bandRoom123',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnOIcyEWOzHdKmsMsbQ1gFjAik36Rczvc',
    appId: '1:500529995449:ios:2f0f54588327d870cdc568',
    messagingSenderId: '500529995449',
    projectId: 'band-room-b6699',
    storageBucket: 'band-room-b6699.firebasestorage.app',
    iosBundleId: 'com.example.bandRoom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4eFX36HIl0pbzMitw8QfZk6KzfQqs6fI',
    appId: '1:500529995449:web:1ffb81520123e5ddcdc568',
    messagingSenderId: '500529995449',
    projectId: 'band-room-b6699',
    authDomain: 'band-room-b6699.firebaseapp.com',
    storageBucket: 'band-room-b6699.firebasestorage.app',
  );
}
